#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2025 OETIKER+PARTNER AG - License: GNU General Public License v2


from typing import Any, Mapping, Optional, Sequence, Union
from cmk.base.check_api import passwordstore_get_cmdline


def agent_nfm_t_arguments(
    params: Mapping[str, Any], hostname: str, ipaddress: Optional[str]
) -> Sequence[Union[str, tuple[str, str, str]]]:
    return [
        elem
        for chunk in (
            ("-u", params["username"]) if "username" in params else (),
            ("-p", passwordstore_get_cmdline("%s", params["password"]))
            if "password" in params
            else (),
            (hostname,),
        )
        for elem in chunk
    ]


special_agent_info["nfm_t"] = agent_nfm_t_arguments
